# Generated by Django 4.2.30 on 2026-04-17 22:06

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nama', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN_DAERAH', 'Admin Daerah'), ('ADMIN_SASANA', 'Admin Sasana'), ('PENGURUS_SASANA', 'Pengurus Sasana'), ('INSTRUKTUR', 'Instruktur'), ('PESERTA', 'Peserta')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Sasana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('propinsi', models.CharField(max_length=100)),
                ('kabupaten', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('kelurahan_desa', models.CharField(max_length=100)),
                ('map', models.CharField(help_text='Koordinat Google Maps', max_length=255)),
                ('profil', models.TextField(blank=True)),
                ('admin_sasana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sasana_managed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_hp', models.CharField(max_length=20)),
                ('tanggal_lahir', models.DateField()),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('berat_badan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tinggi_badan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sasana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasana.sasana')),
            ],
        ),
        migrations.CreateModel(
            name='PengurusSasana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=20)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sasana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasana.sasana')),
            ],
        ),
        migrations.CreateModel(
            name='KeterbatasanFisik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_keterbatasan', models.CharField(max_length=255)),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keterbatasan', to='sasana.peserta')),
            ],
        ),
        migrations.CreateModel(
            name='KendalaKesehatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_penyakit', models.CharField(max_length=255)),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kendala', to='sasana.peserta')),
            ],
        ),
        migrations.CreateModel(
            name='Instruktur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_hp', models.CharField(max_length=20)),
                ('sertifikat', models.CharField(max_length=255)),
                ('id_instruktur', models.CharField(max_length=50, unique=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sasana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasana.sasana')),
            ],
        ),
        migrations.CreateModel(
            name='AdminSasana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sasana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasana.sasana')),
            ],
        ),
        migrations.CreateModel(
            name='AdminDaerah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daerah', models.CharField(max_length=255)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
