# Generated by Django 4.2.30 on 2026-04-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasana', '0002_carouselimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sasana',
            name='profil',
            field=models.ImageField(blank=True, null=True, upload_to='sasana_profiles/'),
        ),
    ]
