# Generated by Django 4.2.30 on 2026-04-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasana', '0003_alter_sasana_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='sasana',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
