# Generated by Django 4.2.30 on 2026-04-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasana', '0004_sasana_alamat'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sasana',
            name='map',
            field=models.CharField(blank=True, help_text='Koordinat Google Maps', max_length=255, null=True),
        ),
    ]
