# Generated by Django 4.2.30 on 2026-05-01 06:05

import django.core.validators
from django.db import migrations, models
import sasana.models


class Migration(migrations.Migration):

    dependencies = [
        ('sasana', '0005_account_force_password_change_alter_sasana_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruktur',
            name='sertifikat',
            field=models.FileField(blank=True, null=True, upload_to='sertifikat/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), sasana.models.Instruktur.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='pengurussasana',
            name='jabatan',
            field=models.CharField(choices=[('Ketua', 'Ketua'), ('Sekretaris', 'Sekretaris'), ('Bendahara', 'Bendahara'), ('Humas', 'Humas')], max_length=100),
        ),
    ]
