# Generated by Django 4.2.30 on 2026-05-01 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sasana', '0006_alter_instruktur_sertifikat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerakanAcuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('membangkitkan semangat', 'Membangkitkan Semangat'), ('cas aki', 'Cas Aki'), ('membangkitkan energi titik nol', 'Membangkitkan Energi Titik Nol'), ('pengendapan', 'Pengendapan')], max_length=50)),
                ('nama_gerakan', models.CharField(max_length=255)),
                ('link_youtube', models.URLField(max_length=500)),
                ('manfaat', models.TextField()),
                ('fokus_gerakan', models.TextField()),
                ('panduan_gerakan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JadwalTerapiSasana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], max_length=50)),
                ('jam_mulai', models.TimeField()),
                ('instruktur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_terapi', to='sasana.instruktur')),
                ('sasana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_terapi', to='sasana.sasana')),
            ],
        ),
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_peserta', models.CharField(max_length=255)),
                ('teks', models.TextField()),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('foto_url', models.ImageField(blank=True, null=True, upload_to='testimoni/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimoni', to='sasana.peserta')),
            ],
        ),
        migrations.CreateModel(
            name='TerapiPeserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_kehadiran', models.CharField(choices=[('Hadir', 'Hadir'), ('Tidak Hadir', 'Tidak Hadir'), ('Izin', 'Izin')], max_length=50)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_peserta', to='terapi.jadwalterapisasana')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_terapi', to='sasana.peserta')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluasiGerakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kesesuaian', models.CharField(choices=[('tidak bisa', 'Tidak Bisa'), ('kurang sesuai', 'Kurang Sesuai'), ('bisa', 'Bisa')], max_length=20)),
                ('catatan_instruktur', models.TextField(blank=True, null=True)),
                ('tanggal_evaluasi', models.DateTimeField(auto_now_add=True)),
                ('gerakan_acuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapi.gerakanacuan')),
                ('instruktur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasana.instruktur')),
                ('terapi_peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluasi', to='terapi.terapipeserta')),
            ],
        ),
    ]
